# Generated by Django 5.2.10 on 2026-02-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('text_input', models.TextField(blank=True, null=True)),
                ('selected_frames', models.JSONField(blank=True, null=True)),
                ('template_schema', models.JSONField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('frame_count', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames/')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meetinginput')),
            ],
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.meetinginput')),
            ],
        ),
    ]
