# Generated by Django 5.2.10 on 2026-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginput',
            name='detected_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meetinginput',
            name='was_translated',
            field=models.BooleanField(default=False),
        ),
    ]
